### ISSUE TITLE
 DETAIL:  Key (permission_view_id, role_id)=(526, 1) already exists.

### ISSUE THREAD

**Issue by bui-theanh** [Armadik/airflow-keycloak-docker-compose#2]
[2024-05-12 09:36:57 +0000] [67] [ERROR] Exception in worker process
airflow-keycloak-docker-compose-airflow-webserver-1    | Traceback (most recent call last):
airflow-keycloak-docker-compose-airflow-webserver-1    |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
airflow-keycloak-docker-compose-airflow-webserver-1    |     cursor, statement, parameters, context
airflow-keycloak-docker-compose-airflow-webserver-1    |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
airflow-keycloak-docker-compose-airflow-webserver-1    |     cursor.execute(statement, parameters)
airflow-keycloak-docker-compose-airflow-webserver-1    | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ab_permission_view_role_permission_view_id_role_id_uq"
airflow-keycloak-docker-compose-airflow-webserver-1    | DETAIL:  Key (permission_view_id, role_id)=(526, 1) already exists.

I am using your docker-compose, I start docker-compose up and see this error, it seems I am wrong somewhere, can you help me?

**Comment by bui-theanh** [comment]
airflow-init-1         | [2024-05-12 09:54:17,433] {init_security.py:64} CRITICAL - Cannot import user_auth for API authentication due to: No module named 'user_auth'
airflow-init-1         | Traceback (most recent call last):
airflow-init-1         |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/extensions/init_security.py", line 60, in init_api_experimental_auth
airflow-init-1         |     auth = import_module(backend.strip())
airflow-init-1         |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
airflow-init-1         |     return _bootstrap._gcd_import(name[level:], package, level)
airflow-init-1         |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
airflow-init-1         |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
airflow-init-1         |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
airflow-init-1         | ModuleNotFoundError: No module named 'user_auth'

**Comment by Armadik** [comment]
restart should help
